### ISSUE TITLE
Question, turn off timeout

### ISSUE THREAD

**Issue by ultraon** [pro100svitlo/FingerprintAuthDemo#5]
Hello, could I turn off timeout 45 sec some how after 5 failing scans?
I don't understand how works cleanTimeout(), what is the cases (example), I tried with it but it didn't work.

**Comment by pro100svitlo** [comment]
Hi!
there are system timeout near 40-45 sec, so after 5  failing scans you need to wait at least this time.
there are method: `cleanTimeOut()`
you can use it in case you set you custom timeout (bigger then default 45 sec)!
For example: there was 5 unsuccessful scan tries, but you have another auth type - pinCode for example. If user enter with pin, then you can try call method `cleanTimeOut()`. If more than default timeOut (45 sec) have passed after 5 scan fails, then method will stop timeoutservice. If less then default timeOut have passed, than method will setUp leftTime as difference between default and passed time.

Is it little bit clear now? :)

**Comment by pro100svitlo** [comment]
@ultraon hi!
can i close this issue?
