### ISSUE TITLE
How can I force my bluetooth to connect only to the smartlock?

### ISSUE THREAD

**Issue by hwalidh** [pro100svitlo/FingerprintAuthDemo#9]
Hi, I am developing an application under Android 6.0. In my application I use bluetooth to connect to a smartlock. I want that when I activate bluetooth my application will only choose the bluetooth of my smartlock. What piece of code will allow me to do that. Thank you.

**Comment by pro100svitlo** [comment]
Hi
I don't understand your purpose and your problem very clear. can you please exmplain them little bit detailed?

**Comment by hwalidh** [comment]
@pro100svitlo I want to implement a button so that when I click on it, it automatically connects to a bluetooth of a smatlock.

**Comment by pro100svitlo** [comment]
@hwalidh 
I am sorry, but it looks like your issue not really related with this library, so I will close this issue.

Anyway, I still don't understand what do you mean by 
> automatically connects to a bluetooth of a smatlock.

This doesn't make sense for me.
Do you want to unlock device via bluetooth?
Or you wand to unlock device via button?

**Comment by hwalidh** [comment]
@pro100svitlo I will try to be more precise.
For example I have 3 smartlock. (S1, S2, S3).
When I click on the button of my application, the S2 opens and not S1 and S3.

**Comment by pro100svitlo** [comment]
maybe this can be helpful for you
http://gadgetguideonline.com/android/lollipop/how-to-use-smart-lock-in-android-lollipop/
